export type AcaClass = {
  id: string;
  name: string;
  month: number; // 5 or 6
  type: string;
  openDate: string;
  teacher: string;
  currentPhase: string;
  phaseStartDate: string;
  phaseStudents: number;
  nextPhaseStartDate: string;
  nextPhase: string;
  slotsToEnroll: number;
};

export type AcaStudent = {
  id: string;
  classId: string;
  stt: number;
  name: string;
  phone: string;
  email: string;
  classification: string;
  scores: {
    l: number | string;
    r: number | string;
    w: number | string;
    s: number | string;
    o: number | string;
  };
  bcbLink: string;
  note: string;
};

export const ACA_CLASSES: AcaClass[] = [
  // --- THÁNG 5 ---
  {
    id: "cls_m5_1",
    name: "XLE RLP_Upstream - 246 - C2 - GV Thái Đỗ Đăng Khoa",
    month: 5,
    type: "Lớp đang diễn ra",
    openDate: "17/09/2024",
    teacher: "Đăng Khoa",
    currentPhase: "S-R",
    phaseStartDate: "18/05/2026",
    phaseStudents: 7,
    nextPhaseStartDate: "29/06/2026",
    nextPhase: "W-L",
    slotsToEnroll: 5,
  },
  {
    id: "cls_m5_2",
    name: "XLE RLP_Upstream - 246 - C2 - GV Tất Duy Khải",
    month: 5,
    type: "Lớp đang diễn ra",
    openDate: "10/02/2025",
    teacher: "Duy Khải",
    currentPhase: "S-R",
    phaseStartDate: "15/05/2026",
    phaseStudents: 4,
    nextPhaseStartDate: "26/06/2026",
    nextPhase: "W-L",
    slotsToEnroll: 8,
  },
  {
    id: "cls_m5_3",
    name: "XLE RLP_Upstream - 357 - C1 - GV Lê Như Hải",
    month: 5,
    type: "Lớp đang diễn ra",
    openDate: "27/03/2025",
    teacher: "Như Hải",
    currentPhase: "W-L",
    phaseStartDate: "20/05/2026",
    phaseStudents: 3,
    nextPhaseStartDate: "01/07/2026",
    nextPhase: "S-R",
    slotsToEnroll: 9,
  },
  {
    id: "cls_m5_4",
    name: "XLE RLP_Upstream - 357 - C2 - GV Tất Duy Khải",
    month: 5,
    type: "Lớp đang diễn ra",
    openDate: "27/06/2024",
    teacher: "Duy Khải",
    currentPhase: "W-L",
    phaseStartDate: "29/05/2026",
    phaseStudents: 5,
    nextPhaseStartDate: "10/07/2026",
    nextPhase: "S-R",
    slotsToEnroll: 7,
  },
  {
    id: "cls_m5_5",
    name: "XLE RLP_Momentum - 357 - C1 - GV Nguyễn Lê Trung Dũng",
    month: 5,
    type: "Lớp đang diễn ra",
    openDate: "24/03/2026",
    teacher: "Trung Dũng",
    currentPhase: "W-L",
    phaseStartDate: "02/06/2026",
    phaseStudents: 5,
    nextPhaseStartDate: "14/07/2026",
    nextPhase: "S-R",
    slotsToEnroll: 5,
  },
  {
    id: "cls_m5_6",
    name: "XLE RLP_Momentum - 246 - C2 - GV Lê Như Hải",
    month: 5,
    type: "Lớp đang diễn ra",
    openDate: "03/05/2024",
    teacher: "Như Hải",
    currentPhase: "S-R",
    phaseStartDate: "18/05/2026",
    phaseStudents: 3,
    nextPhaseStartDate: "29/06/2026",
    nextPhase: "W-L",
    slotsToEnroll: 7,
  },
  {
    id: "cls_m5_7",
    name: "XLE RLP_Soar - S/S - C1 - GV Nguyễn Lưu Minh Tâm",
    month: 5,
    type: "Lớp đang diễn ra",
    openDate: "06/12/2025",
    teacher: "Minh Tâm",
    currentPhase: "W-L",
    phaseStartDate: "21/05/2026",
    phaseStudents: 1,
    nextPhaseStartDate: "02/07/2026",
    nextPhase: "S-R",
    slotsToEnroll: 11,
  },
  {
    id: "cls_m5_8",
    name: "XLE RLP_Soar - 246 - C2 - GV Trần Quang Minh",
    month: 5,
    type: "Lớp đang diễn ra",
    openDate: "28/10/2024",
    teacher: "Quang Minh",
    currentPhase: "W-L",
    phaseStartDate: "20/05/2026",
    phaseStudents: 3,
    nextPhaseStartDate: "01/07/2026",
    nextPhase: "S-R",
    slotsToEnroll: 9,
  },
  {
    id: "cls_m5_9",
    name: "XLE RLP_Soar - 357 - C2 - GV Lê Như Hải",
    month: 5,
    type: "Lớp đang diễn ra",
    openDate: "29/10/2024",
    teacher: "Như Hải",
    currentPhase: "S-R",
    phaseStartDate: "23/05/2026",
    phaseStudents: 2,
    nextPhaseStartDate: "04/07/2026",
    nextPhase: "W-L",
    slotsToEnroll: 10,
  },

  // --- THÁNG 6 ---
  {
    id: "cls_m6_1",
    name: "XLE RLP_Upstream - 246 - C1 - GV Tất Duy Khải",
    month: 6,
    type: "Lớp đang diễn ra",
    openDate: "26/08/2024",
    teacher: "Duy Khải",
    currentPhase: "S-R",
    phaseStartDate: "29/04/2026",
    phaseStudents: 2,
    nextPhaseStartDate: "12/06/2026",
    nextPhase: "W-L",
    slotsToEnroll: 10,
  },
  {
    id: "cls_m6_2",
    name: "XLE RLP_Upstream - 246 - C2 - GV Tất Duy Khải",
    month: 6,
    type: "Lớp đang diễn ra",
    openDate: "10/02/2025",
    teacher: "Duy Khải",
    currentPhase: "W-L",
    phaseStartDate: "26/06/2026",
    phaseStudents: 2,
    nextPhaseStartDate: "07/08/2026",
    nextPhase: "S-R",
    slotsToEnroll: 10,
  },
  {
    id: "cls_m6_3",
    name: "XLE RLP_Upstream - 246 - C2 - GV Thái Đỗ Đăng Khoa",
    month: 6,
    type: "Lớp đang diễn ra",
    openDate: "17/09/2024",
    teacher: "Đăng Khoa",
    currentPhase: "W-L",
    phaseStartDate: "29/06/2026",
    phaseStudents: 7,
    nextPhaseStartDate: "10/08/2026",
    nextPhase: "S-R",
    slotsToEnroll: 5,
  },
  {
    id: "cls_m6_4",
    name: "XLE RLP_Upstream - 357 - C1 - GV Lê Như Hải",
    month: 6,
    type: "Lớp đang diễn ra",
    openDate: "27/03/2025",
    teacher: "Như Hải",
    currentPhase: "S-R",
    phaseStartDate: "01/07/2026",
    phaseStudents: 3,
    nextPhaseStartDate: "12/08/2026",
    nextPhase: "W-L",
    slotsToEnroll: 9,
  },
  {
    id: "cls_m6_5",
    name: "XLE RLP_Upstream - 357 - C2 - GV Tất Duy Khải",
    month: 6,
    type: "Lớp đang diễn ra",
    openDate: "27/06/2024",
    teacher: "Duy Khải",
    currentPhase: "S-R",
    phaseStartDate: "10/07/2026",
    phaseStudents: 5,
    nextPhaseStartDate: "21/08/2026",
    nextPhase: "W-L",
    slotsToEnroll: 7,
  },
  {
    id: "cls_m6_6",
    name: "XLE RLP_Upstream - S/S - C1 - GV Nghiêm Doãn Quỳnh Châu",
    month: 6,
    type: "Lớp đang diễn ra",
    openDate: "18/04/2026",
    teacher: "Quỳnh Châu",
    currentPhase: "S-R",
    phaseStartDate: "26/07/2026",
    phaseStudents: 4,
    nextPhaseStartDate: "12/09/2026",
    nextPhase: "W-L",
    slotsToEnroll: 8,
  },
  {
    id: "cls_m6_7",
    name: "XLE RLP_Momentum - 246 - C1 - GV Lê Như Hải",
    month: 6,
    type: "Lớp đang diễn ra",
    openDate: "26/08/2024",
    teacher: "Như Hải",
    currentPhase: "S-R",
    phaseStartDate: "04/05/2026",
    phaseStudents: 3,
    nextPhaseStartDate: "15/06/2026",
    nextPhase: "W-L",
    slotsToEnroll: 7,
  },
  {
    id: "cls_m6_8",
    name: "XLE RLP_Momentum - 246 - C2 - GV Lê Như Hải",
    month: 6,
    type: "Lớp đang diễn ra",
    openDate: "03/05/2024",
    teacher: "Như Hải",
    currentPhase: "W-L",
    phaseStartDate: "29/06/2026",
    phaseStudents: 2,
    nextPhaseStartDate: "10/08/2026",
    nextPhase: "S-R",
    slotsToEnroll: 8,
  },
  {
    id: "cls_m6_9",
    name: "XLE RLP_Momentum - 357 - C1 - GV Nguyễn Lê Trung Dũng",
    month: 6,
    type: "Lớp đang diễn ra",
    openDate: "24/03/2026",
    teacher: "Trung Dũng",
    currentPhase: "S-R",
    phaseStartDate: "25/08/2026",
    phaseStudents: 1,
    nextPhaseStartDate: "06/10/2026",
    nextPhase: "W-L",
    slotsToEnroll: 9,
  },
  {
    id: "cls_m6_10",
    name: "XLE RLP_Momentum - 357 - C2 - GV Nghiêm Doãn Quỳnh Châu",
    month: 6,
    type: "Lớp đang diễn ra",
    openDate: "21/04/2026",
    teacher: "Quỳnh Châu",
    currentPhase: "W-L",
    phaseStartDate: "21/04/2026",
    phaseStudents: 4,
    nextPhaseStartDate: "11/06/2026",
    nextPhase: "S-R",
    slotsToEnroll: 6,
  },
  {
    id: "cls_m6_11",
    name: "XLE RLP_Soar - 246 - C1 - GV Trần Quang Minh",
    month: 6,
    type: "Lớp đang diễn ra",
    openDate: "28/06/2024",
    teacher: "Quang Minh",
    currentPhase: "W-L",
    phaseStartDate: "10/07/2026",
    phaseStudents: 2,
    nextPhaseStartDate: "21/08/2026",
    nextPhase: "S-R",
    slotsToEnroll: 10,
  },
  {
    id: "cls_m6_12",
    name: "XLE RLP_Soar - 246 - C2 - GV Trần Quang Minh",
    month: 6,
    type: "Lớp đang diễn ra",
    openDate: "28/10/2024",
    teacher: "Quang Minh",
    currentPhase: "S-R",
    phaseStartDate: "01/07/2026",
    phaseStudents: 2,
    nextPhaseStartDate: "12/08/2026",
    nextPhase: "W-L",
    slotsToEnroll: 10,
  },
  {
    id: "cls_m6_13",
    name: "XLE RLP_Soar - 357 - C2 - GV Lê Như Hải",
    month: 6,
    type: "Lớp đang diễn ra",
    openDate: "29/10/2024",
    teacher: "Như Hải",
    currentPhase: "W-L",
    phaseStartDate: "07/07/2026",
    phaseStudents: 2,
    nextPhaseStartDate: "15/08/2026",
    nextPhase: "S-R",
    slotsToEnroll: 10,
  },
  {
    id: "cls_m6_14",
    name: "XLE RLP_Soar - S/S - C1 - GV Nguyễn Lưu Minh Tâm",
    month: 6,
    type: "Lớp đang diễn ra",
    openDate: "06/12/2025",
    teacher: "Minh Tâm",
    currentPhase: "S-R",
    phaseStartDate: "05/07/2026",
    phaseStudents: 3,
    nextPhaseStartDate: "13/08/2026",
    nextPhase: "W-L",
    slotsToEnroll: 9,
  },
  {
    id: "cls_m6_15",
    name: "XLE RLP_Advanced - 246 - C1 - GV Nguyễn Lê Trung Dũng",
    month: 6,
    type: "Lớp đang diễn ra",
    openDate: "25/03/2026",
    teacher: "Đăng Duy",
    currentPhase: "S-R",
    phaseStartDate: "22/06/2026",
    phaseStudents: 2,
    nextPhaseStartDate: "03/08/2026",
    nextPhase: "W-L",
    slotsToEnroll: 8,
  },
  {
    id: "cls_m6_16",
    name: "XLE RLP_PRE CORE - 246 - 18002000 - GV Minh Tâm",
    month: 6,
    type: "Lớp đang diễn ra",
    openDate: "13/04/2026",
    teacher: "Minh Tâm",
    currentPhase: "Pre IELTS",
    phaseStartDate: "13/04/2026",
    phaseStudents: 6,
    nextPhaseStartDate: "15/06/2026",
    nextPhase: "CORE 2",
    slotsToEnroll: 6,
  },
  {
    id: "cls_m6_17",
    name: "XLE RLP_PRE CORE - 357 - 20002200 - GV Thanh Tâm",
    month: 6,
    type: "Lớp đang diễn ra",
    openDate: "14/04/2026",
    teacher: "Thanh Tâm",
    currentPhase: "Pre IELTS",
    phaseStartDate: "14/04/2026",
    phaseStudents: 3,
    nextPhaseStartDate: "11/06/2026",
    nextPhase: "CORE 2",
    slotsToEnroll: 9,
  },
  {
    id: "cls_m6_18",
    name: "XLE RLP_PRE CORE - 246 - 20002200 / 220526 - GV Quỳnh Châu",
    month: 6,
    type: "Lớp đang diễn ra",
    openDate: "22/05/2026",
    teacher: "Quỳnh Châu",
    currentPhase: "Pre IELTS",
    phaseStartDate: "22/05/2026",
    phaseStudents: 3,
    nextPhaseStartDate: "17/07/2026",
    nextPhase: "CORE 2",
    slotsToEnroll: 9,
  },
  {
    id: "cls_m6_19",
    name: "XLE RLP_PRE CORE - 357 - 18002000 / 230526 - GV Thanh Tâm",
    month: 6,
    type: "Lớp đang diễn ra",
    openDate: "23/05/2026",
    teacher: "Thanh Tâm",
    currentPhase: "Pre IELTS",
    phaseStartDate: "23/05/2026",
    phaseStudents: 4,
    nextPhaseStartDate: "18/07/2026",
    nextPhase: "CORE 2",
    slotsToEnroll: 8,
  },
  {
    id: "cls_m6_20",
    name: "XLE RLP_Foundation - 357 - C2 - GV Đăng Duy",
    month: 6,
    type: "Lớp mới",
    openDate: "18/06/2026",
    teacher: "Đăng Duy",
    currentPhase: "-",
    phaseStartDate: "-",
    phaseStudents: 0,
    nextPhaseStartDate: "18/06/2026",
    nextPhase: "-",
    slotsToEnroll: 10,
  },
];

export const ACA_STUDENTS: AcaStudent[] = [
  // --- THÁNG 5 HỌC VIÊN ---
  {
    id: "st_m5_1",
    classId: "cls_m5_1",
    stt: 1,
    name: "Nguyễn Thị Ngọc Hân",
    phone: "0775399613",
    email: "ngochan279a@gmail.com",
    classification: "Học viên cũ học lại",
    scores: { l: 6.0, r: 6.0, w: 5.5, s: 4.5, o: 5.5 },
    bcbLink: "https://docs.google.com/spreadsheets/d/1pkBwIMZI3nVaZjHpMbK-PLztc5jgs8G3hxlKVOcffNA/edit",
    note: "",
  },
  {
    id: "st_m5_2",
    classId: "cls_m5_1",
    stt: 2,
    name: "Trần Tuệ Linh",
    phone: "352796806",
    email: "alexandradiamond009@gmail.com",
    classification: "Học viên combo học tiếp",
    scores: { l: 5.5, r: 5.5, w: 5.5, s: 4.5, o: 5.5 },
    bcbLink: "https://docs.google.com/spreadsheets/d/14ISNNxxfyJqMF4wiV71Am-hLzQUtyoAgxBOMPvdexR0/edit?usp=sharing",
    note: "",
  },
  {
    id: "st_m5_3",
    classId: "cls_m5_1",
    stt: 3,
    name: "Phạm Lê Thảo Nhi",
    phone: "848142696",
    email: "missthaonhi2003@gmail.com",
    classification: "Học viên lớp C 19/1 tái đóng",
    scores: { l: 5.0, r: 5.5, w: 5.5, s: 4.5, o: 5.0 },
    bcbLink: "https://docs.google.com/spreadsheets/d/1RqeuqpdTHVcv8RuE_D6Fu5l64mZZnyvJ7EfC11zJHu0/edit?usp=sharing",
    note: "",
  },
  {
    id: "st_m5_4",
    classId: "cls_m5_1",
    stt: 4,
    name: "Cao Thanh Lâm",
    phone: "365756145",
    email: "thanhlamcao210@gmail.com",
    classification: "Học viên lớp C 14/10",
    scores: { l: 5.0, r: 5.0, w: 1.0, s: 4.0, o: "4.0/4.5" },
    bcbLink: "https://docs.google.com/spreadsheets/d/1hNKxO28r4lt3H0lRko16rEZl4go4RxrWthztXE0ZaHM/edit",
    note: "",
  },

  // --- THÁNG 6 HỌC VIÊN ---
  {
    id: "st_m6_1",
    classId: "cls_m6_1",
    stt: 1,
    name: "Vũ Thị Thùy",
    phone: "976664376",
    email: "tvt8489@gmail.com",
    classification: "Học viên cũ học lại",
    scores: { l: 5.5, r: 5.5, w: 6.5, s: 5.0, o: 5.5 },
    bcbLink: "https://docs.google.com/spreadsheets/d/1dlzuLPaixPm1XttFwCvvn13-va2xjYvXXJajiiz3qgA/edit?usp=sharing",
    note: "",
  },
  {
    id: "st_m6_2",
    classId: "cls_m6_1",
    stt: 2,
    name: "Lê Phạm Huyền My",
    phone: "837725134",
    email: "phammy08029@gmail.com",
    classification: "Học viên combo học tiếp",
    scores: { l: "-", r: "-", w: 5.0, s: 4.0, o: "-" },
    bcbLink: "https://drive.google.com/open?id=1FSvfkBbsQQNNPzxeGRJuuqW8dPiCdLMCVEKA9Jb6URs",
    note: "11/6 mới làm final L-R",
  },
  {
    id: "st_m6_3",
    classId: "cls_m6_1",
    stt: 3,
    name: "Hồ Thị Thu",
    phone: "0344398257",
    email: "hothu736@gmail.com",
    classification: "Học viên combo học tiếp",
    scores: { l: 5.5, r: 6.5, w: 5.0, s: 4.5, o: 5.5 },
    bcbLink: "https://docs.google.com/spreadsheets/d/1GZMK7RiadZKl6Ki6nC56-rvQ4Hx_X-uVFrEXYI6cwiI/edit?gid=1425079543#gid=1425079543",
    note: "",
  },
  {
    id: "st_m6_4",
    classId: "cls_m6_1",
    stt: 4,
    name: "Dương Quang Đức Minh",
    phone: "336863109",
    email: "fbchinhcuaminh@gmail.com",
    classification: "Học viên combo học tiếp",
    scores: { l: 5.5, r: 6.0, w: 4.5, s: 3.5, o: 5.0 },
    bcbLink: "https://drive.google.com/open?id=1oN1n1kQHecgpHgcBpO3ZQzF2zBMOkS4APseEGGWsWEo",
    note: "",
  },
  {
    id: "st_m6_5",
    classId: "cls_m6_2",
    stt: 1,
    name: "Phạm Hà Linh",
    phone: "-",
    email: "-",
    classification: "Học viên C 1/4",
    scores: { l: "-", r: "-", w: "-", s: "-", o: "-" },
    bcbLink: "",
    note: "",
  },
  {
    id: "st_m6_6",
    classId: "cls_m6_2",
    stt: 2,
    name: "Vũ Trúc Linh",
    phone: "-",
    email: "-",
    classification: "Học viên C 1/4",
    scores: { l: "-", r: "-", w: "-", s: "-", o: "-" },
    bcbLink: "",
    note: "",
  },
  {
    id: "st_m6_7",
    classId: "cls_m6_3",
    stt: 1,
    name: "Bùi Minh Đăng",
    phone: "567255266",
    email: "buiminhdang261@gmail.com",
    classification: "Học viên mới",
    scores: { l: "-", r: "-", w: "-", s: "-", o: "-" },
    bcbLink: "",
    note: "",
  },
  {
    id: "st_m6_8",
    classId: "cls_m6_3",
    stt: 2,
    name: "Lê Phương Hà",
    phone: "0848992009",
    email: "lephuongha209@gmail.com",
    classification: "Học viên mới",
    scores: { l: "-", r: "-", w: "-", s: "-", o: "-" },
    bcbLink: "",
    note: "",
  },
  {
    id: "st_m6_9",
    classId: "cls_m6_6",
    stt: 1,
    name: "Đoàn Phạm Khánh Linh",
    phone: "339527876",
    email: "pham34410@gmail.com",
    classification: "Học viên combo học tiếp",
    scores: { l: 6.5, r: 6.5, w: 5.0, s: 4.5, o: 5.5 },
    bcbLink: "https://docs.google.com/spreadsheets/d/1er3-hZ8Zl0ug3yn63zqqVShcQs8i2AlyPN6rzLJzotY/edit?gid=1425079543#gid=1425079543",
    note: "",
  },
  {
    id: "st_m6_10",
    classId: "cls_m6_6",
    stt: 2,
    name: "Nguyễn Thịnh Phát",
    phone: "964200448",
    email: "ntphat2112007@gmail.com",
    classification: "Học viên cũ học lại",
    scores: { l: 5.5, r: 5.5, w: 3.0, s: 3.0, o: 4.5 },
    bcbLink: "https://docs.google.com/spreadsheets/d/108LISYO6uQ6_sdfJGl-FeBCHj_KIrUY9E528zh5FQdM/edit?gid=1425079543#gid=1425079543",
    note: "",
  },
  {
    id: "st_m6_11",
    classId: "cls_m6_6",
    stt: 3,
    name: "Phạm Thị Thanh Thảo",
    phone: "962623933",
    email: "phamthanhthao24022009@gmail.com",
    classification: "Học viên mới",
    scores: { l: 5.0, r: 4.5, w: 5.0, s: 4.0, o: 4.5 },
    bcbLink: "https://docs.google.com/spreadsheets/d/1eaG-_PD-ibVM9EIEVIemps99t73e47WOu9hbxXulr60/edit?gid=1425079543#gid=1425079543",
    note: "",
  },
  {
    id: "st_m6_12",
    classId: "cls_m6_8",
    stt: 1,
    name: "Trần Võ Mai Hương",
    phone: "0832150576",
    email: "maihuongtran1209@gmail.com",
    classification: "Học bổng Hè 20%",
    scores: { l: 5.5, r: 5.5, w: 2.5, s: 4.5, o: 4.5 },
    bcbLink: "Trần Võ Mai Hương",
    note: "Học bổng Hè 20%",
  },
  {
    id: "st_m6_13",
    classId: "cls_m6_12",
    stt: 1,
    name: "Lưu Nguyễn Thụy Khuê",
    phone: "0344530061",
    email: "luukelly669@gmail.com",
    classification: "Học viên mới",
    scores: { l: "-", r: "-", w: "-", s: "-", o: "-" },
    bcbLink: "",
    note: "",
  },
  {
    id: "st_m6_14",
    classId: "cls_m6_13",
    stt: 1,
    name: "Lưu Thị Hoài Thương",
    phone: "0822511233",
    email: "luuhoaithuong333@gmail.com",
    classification: "Học viên mới",
    scores: { l: 5.5, r: 8.5, w: 6.0, s: 6.5, o: 6.5 },
    bcbLink: "",
    note: "",
  },
  {
    id: "st_m6_15",
    classId: "cls_m6_13",
    stt: 2,
    name: "Hồ Trúc Lâm",
    phone: "-",
    email: "-",
    classification: "học viên chuyển lớp",
    scores: { l: "-", r: "-", w: "-", s: "-", o: "-" },
    bcbLink: "",
    note: "",
  },
  {
    id: "st_m6_16",
    classId: "cls_m6_16",
    stt: 1,
    name: "Trần Thanh Vũ",
    phone: "0816866472",
    email: "tranthanhvudeptrai369@gmail.com",
    classification: "Học viên mới",
    scores: { l: 3.0, r: 3.5, w: 2.5, s: 4.0, o: 3.5 },
    bcbLink: "",
    note: "Trần Thanh Vũ",
  },
  {
    id: "st_m6_17",
    classId: "cls_m6_16",
    stt: 2,
    name: "Nguyễn Đặng Bảo Trâm",
    phone: "0365110889",
    email: "nguyendangbaotram.2009@gmail.com",
    classification: "Học viên mới",
    scores: { l: 5.5, r: 6.0, w: 3.0, s: 3.0, o: 4.5 },
    bcbLink: "",
    note: "Nguyễn Đặng Bảo trâm",
  },
  {
    id: "st_m6_18",
    classId: "cls_m6_16",
    stt: 3,
    name: "Lê Thị Kim Hà",
    phone: "339637609",
    email: "hale28012009@gmail.com",
    classification: "Học viên mới",
    scores: { l: 2.0, r: 4.5, w: 2.5, s: 5.0, o: 3.5 },
    bcbLink: "",
    note: "Lê Thị Kim Hà",
  },
  {
    id: "st_m6_19",
    classId: "cls_m6_16",
    stt: 4,
    name: "Trần Anh Thư",
    phone: "0977391703",
    email: "tranlathu@gmail.com",
    classification: "Học viên mới",
    scores: { l: 2.5, r: 4.0, w: 0, s: 3.0, o: 3.5 },
    bcbLink: "",
    note: "Trần Anh Thư",
  },
  {
    id: "st_m6_20",
    classId: "cls_m6_17",
    stt: 1,
    name: "Lê Thị Ngọc Doanh",
    phone: "0942717101",
    email: "doanhl438@gmail.com",
    classification: "Học viên mới",
    scores: { l: 2.5, r: 3.5, w: "-", s: 2.5, o: "-" },
    bcbLink: "",
    note: "Lê Thị Ngọc Doanh",
  },
  {
    id: "st_m6_21",
    classId: "cls_m6_17",
    stt: 2,
    name: "Trần Thị Quỳnh Như",
    phone: "0352792228",
    email: "quynhnhutran172006@gmail.com",
    classification: "Học viên mới",
    scores: { l: 4.5, r: 5.0, w: "-", s: 4.5, o: "-" },
    bcbLink: "",
    note: "Trần Thị Quỳnh Như",
  },
  {
    id: "st_m6_22",
    classId: "cls_m6_17",
    stt: 3,
    name: "Nguyễn Thảo Phương",
    phone: "0355794451",
    email: "stonce3101@gmail.com",
    classification: "Học viên mới",
    scores: { l: "-", r: "-", w: "-", s: "-", o: 4.5 },
    bcbLink: "",
    note: "Nguyễn Thảo Phương",
  },
  {
    id: "st_m6_23",
    classId: "cls_m6_17",
    stt: 4,
    name: "Nguyễn Đinh Như Ngọc",
    phone: "383029945",
    email: "ngdinhnhungoc@gmail.com",
    scores: { l: 3.5, r: 3.5, w: 3.0, s: 3.0, o: 3.5 },
    classification: "Học viên mới",
    bcbLink: "https://docs.google.com/spreadsheets/d/10EMptaogKmdZMNVndDhoULjJMp5yWjlhfMXBV2D5glA/edit?usp=drivesdk",
    note: "",
  },
  {
    id: "st_m6_24",
    classId: "cls_m6_19",
    stt: 1,
    name: "Nguyễn Thị Ngân",
    phone: "0968087805",
    email: "nguyenngan01082005@gmail.com",
    classification: "Học viên mới",
    scores: { l: "-", r: "-", w: "-", s: "-", o: "-" },
    bcbLink: "",
    note: "",
  },
  {
    id: "st_m6_25",
    classId: "cls_m6_19",
    stt: 2,
    name: "Bùi Kim Quỳnh",
    phone: "0888880939",
    email: "Buiquin.105@gmail.com",
    classification: "Học viên cũ học lại",
    scores: { l: "-", r: "-", w: "-", s: "-", o: "-" },
    bcbLink: "",
    note: "",
  },
  {
    id: "st_m6_26",
    classId: "cls_m6_19",
    stt: 3,
    name: "Hà Nguyễn Bảo Ngọc",
    phone: "-",
    email: "-",
    classification: "Học viên PC 13/4 đổi lớp",
    scores: { l: "-", r: "-", w: "-", s: "-", o: "-" },
    bcbLink: "",
    note: "",
  },
  {
    id: "st_m6_27",
    classId: "cls_m6_20",
    stt: 1,
    name: "Nguyễn Lê Yến Nhi",
    phone: "0336281031",
    email: "nguyenleyennhi1910@gmail.com",
    classification: "Học viên mới",
    scores: { l: "-", r: "-", w: "-", s: "-", o: "-" },
    bcbLink: "",
    note: "",
  },
  {
    id: "st_m6_28",
    classId: "cls_m6_20",
    stt: 2,
    name: "Nguyễn Thị Huỳnh Như",
    phone: "0913785162",
    email: "huynhnhuthinguyen28@gmail.com",
    classification: "Học viên mới",
    scores: { l: 3.0, r: 3.5, w: 0, s: 2.5, o: 2.5 },
    bcbLink: "https://docs.google.com/spreadsheets/d/1-Xs5nCJJRO-1E199g5IjxXPIoTSdA1NaC3DrLVeaGxg/edit",
    note: "",
  },
  {
    id: "st_m6_29",
    classId: "cls_m6_20",
    stt: 3,
    name: "Nguyễn Ngọc Như Ý",
    phone: "0962928312",
    email: "ngngocnhuy0806@gmail.com",
    classification: "Học viên mới",
    scores: { l: 4.0, r: 2.0, w: 0, s: 3.5, o: 2.5 },
    bcbLink: "https://docs.google.com/spreadsheets/d/1JUlSpBg_UeD1UW9P_1Smi_S2610EbZOBL1pJ-swSDX0/edit",
    note: "",
  },
  {
    id: "st_m6_30",
    classId: "cls_m6_20",
    stt: 4,
    name: "Lê Tuyền Duy",
    phone: "0941 985 845",
    email: "tuyenduyle791999@gmail.com",
    classification: "Học viên mới",
    scores: { l: "-", r: "-", w: "-", s: "-", o: "-" },
    bcbLink: "",
    note: "",
  },
];

export type AcaPracticeStudent = {
  id: string;
  stt: number;
  name: string;
  phone: string;
  rlp: string;
  testScheduleSunday: string;
  scheduleTueSat: string;
  participateLd28: boolean;
  note: string;
  weekRange: string; // e.g. "20/04 - 26/04", "27/04 - 03/05", "08/06 - 14/06"
};

export type AcaPracticeWeekInfo = {
  weekRange: string;
  linkMeet: string;
  linkTab: string;
  announcement: string;
  templateMessage: string;
};

export const ACA_PRACTICE_WEEKS: AcaPracticeWeekInfo[] = [
  {
    weekRange: "20/04/2026 - 26/04/2026",
    linkMeet: "https://meet.google.com/abc-defg-hij",
    linkTab: "https://docs.google.com/spreadsheets/d/1track-practice-test-1",
    announcement: `[Thông báo về lịch học lớp LĐ]

Tuần 20/4:
 - Lớp có học Speaking vào 19h45-21h45 thứ 7 25/4
 - Lớp không có lịch test tập trung vào CN

Nhận được tin thì em react/confirm giúp chị nhé`,
    templateMessage: "Em ơi, chủ nhật tuần này (26/4) lớp mình không có lịch test tập trung, các bạn tham gia học Speaking vào thứ 7 (25/4) lúc 19h45-21h45 nhé!",
  },
  {
    weekRange: "27/04/2026 - 03/05/2026",
    linkMeet: "https://meet.google.com/abc-defg-hij",
    linkTab: "https://docs.google.com/spreadsheets/d/1track-practice-test-2",
    announcement: `[Thông báo về lịch học lớp LĐ]

Tuần 27/4:
 - Lớp nghỉ, không có lịch học vào T3 và T7
 - Lớp có lịch test tập trung vào CN 3/5 9h-11h30

Nhận được tin thì em react/confirm giúp chị nhé`,
    templateMessage: "Em ơi, chủ nhật tuần này (3/5) chị có lịch test lớp luyện đề lúc 9h00 - 11h30, em tham gia được thì phản hồi lại giúp chị nha!",
  },
  {
    weekRange: "08/06/2026 - 14/06/2026",
    linkMeet: "https://meet.google.com/xyz-uvwx-yza",
    linkTab: "https://docs.google.com/spreadsheets/d/1track-practice-test-3",
    announcement: `[Thông báo về lịch học lớp LĐ]

Tuần 8/6:
 - Lớp học bình thường vào thứ 3 và thứ 7
 - Lớp có lịch test tập trung vào CN 14/6 9h-11h30

Nhận được tin thì em react/confirm giúp chị nhé`,
    templateMessage: "Em ơi, chủ nhật tuần này (14/6) chị có lịch test lớp luyện đề lúc 9h00 - 11h30, em tham gia được thì phản hồi lại giúp chị nha!",
  },
];

export const ACA_PRACTICE_STUDENTS: AcaPracticeStudent[] = [
  {
    id: "p1",
    stt: 1,
    name: "Trần Kiều My",
    phone: "397672066",
    rlp: "RLP Trần Kiều My - 09022501CC5",
    testScheduleSunday: "Có tham gia",
    scheduleTueSat: "có test, đang sắp xếp thời gian học",
    participateLd28: false,
    note: "",
    weekRange: "08/06/2026 - 14/06/2026",
  },
  {
    id: "p2",
    stt: 2,
    name: "Bùi Phạm Diệu Linh",
    phone: "0343311238",
    rlp: "RLP Bùi Phạm Diệu Linh - 30092503CC2",
    testScheduleSunday: "Có tham gia",
    scheduleTueSat: "",
    participateLd28: false,
    note: "",
    weekRange: "08/06/2026 - 14/06/2026",
  },
  {
    id: "p3",
    stt: 3,
    name: "Nguyễn Hoà Gia Liên",
    phone: "-",
    rlp: "RLP Nguyễn Hòa Gia Liên - 23082502CC4",
    testScheduleSunday: "Gửi đề vào CN",
    scheduleTueSat: "",
    participateLd28: false,
    note: "",
    weekRange: "08/06/2026 - 14/06/2026",
  },
  {
    id: "p4",
    stt: 4,
    name: "Nguyễn Ngọc Mai",
    phone: "353514489",
    rlp: "RLP Nguyễn Ngọc Mai - 16092503CC4",
    testScheduleSunday: "Có tham gia",
    scheduleTueSat: "",
    participateLd28: false,
    note: "12/3 hong tham gia",
    weekRange: "08/06/2026 - 14/06/2026",
  },
  {
    id: "p5",
    stt: 5,
    name: "Lê Trần Bảo Thy",
    phone: "948928401",
    rlp: "RLP Lê Trần Bảo Thy - 28062402CC4",
    testScheduleSunday: "Đăng ký lịch khác",
    scheduleTueSat: "",
    participateLd28: true,
    note: "",
    weekRange: "08/06/2026 - 14/06/2026",
  },
  {
    id: "p6",
    stt: 6,
    name: "Đoàn Quỳnh Hương",
    phone: "828685589",
    rlp: "RLP Đoàn Quỳnh Hương - 29102501CC4",
    testScheduleSunday: "Đăng ký lịch khác",
    scheduleTueSat: "",
    participateLd28: false,
    note: "T7: 9h - 11h",
    weekRange: "08/06/2026 - 14/06/2026",
  },
  {
    id: "p7",
    stt: 7,
    name: "Cao Thị Ngọc Trâm",
    phone: "0976496294",
    rlp: "RLP Cao Thị Ngọc Trâm - 25092501CC4",
    testScheduleSunday: "Gửi đề vào CN",
    scheduleTueSat: "đã sắp xếp để test tiếp, vẫn tham gia học",
    participateLd28: false,
    note: "",
    weekRange: "08/06/2026 - 14/06/2026",
  },
  {
    id: "p8",
    stt: 8,
    name: "Cao Thị Lan Anh",
    phone: "0928740296",
    rlp: "RLP Cao Thị Lan Anh - 28062401CC4",
    testScheduleSunday: "Đăng ký lịch khác",
    scheduleTueSat: "",
    participateLd28: false,
    note: "",
    weekRange: "08/06/2026 - 14/06/2026",
  },
  {
    id: "p9",
    stt: 9,
    name: "Nguyễn Thị Vân Trang",
    phone: "0379326300",
    rlp: "RLP Nguyễn Thị Vân Trang - 18082501CC1",
    testScheduleSunday: "Có tham gia",
    scheduleTueSat: "hong tham gia học được",
    participateLd28: false,
    note: "",
    weekRange: "08/06/2026 - 14/06/2026",
  },
  {
    id: "p10",
    stt: 10,
    name: "Hồ Lê Thanh Huy",
    phone: "853101105",
    rlp: "RLP Hồ Lê Thanh Huy - 15092501CC2",
    testScheduleSunday: "Gửi đề vào CN",
    scheduleTueSat: "bận rồi tạm hong học nhưng vẫn muốn nhận đề",
    participateLd28: false,
    note: "",
    weekRange: "08/06/2026 - 14/06/2026",
  },
  {
    id: "p11",
    stt: 11,
    name: "Lưu Anh Tài",
    phone: "376498451",
    rlp: "RLP Lưu Anh Tài - 17052504CC2",
    testScheduleSunday: "Có tham gia",
    scheduleTueSat: "",
    participateLd28: false,
    note: "",
    weekRange: "08/06/2026 - 14/06/2026",
  },
  {
    id: "p12",
    stt: 12,
    name: "Lê Minh Vững",
    phone: "965287152",
    rlp: "RLP Lê Minh Vững - 12112401CC2",
    testScheduleSunday: "Có tham gia",
    scheduleTueSat: "",
    participateLd28: false,
    note: "",
    weekRange: "08/06/2026 - 14/06/2026",
  },
  {
    id: "p13",
    stt: 13,
    name: "Lê Kim Phụng",
    phone: "0888187848",
    rlp: "RLP Lê Kim Phụng - 22072301CC1",
    testScheduleSunday: "Có tham gia",
    scheduleTueSat: "",
    participateLd28: false,
    note: "",
    weekRange: "08/06/2026 - 14/06/2026",
  },
  {
    id: "p14",
    stt: 14,
    name: "Nguyễn Thảo Hiền",
    phone: "345050855",
    rlp: "RLP Nguyễn Thảo Hiền - 30062503CC4",
    testScheduleSunday: "Có tham gia",
    scheduleTueSat: "",
    participateLd28: false,
    note: "hong reply",
    weekRange: "08/06/2026 - 14/06/2026",
  },
  {
    id: "p15",
    stt: 15,
    name: "Nguyễn Thịnh Phát",
    phone: "-",
    rlp: "RLP Nguyễn Thịnh Phát - 22012601CC2",
    testScheduleSunday: "Gửi đề vào CN",
    scheduleTueSat: "",
    participateLd28: false,
    note: "",
    weekRange: "08/06/2026 - 14/06/2026",
  },
  {
    id: "p16",
    stt: 16,
    name: "Nguyễn Thị Kiều Oanh",
    phone: "-",
    rlp: "RLP Nguyễn Thị Kiều Oanh",
    testScheduleSunday: "Gửi đề vào CN",
    scheduleTueSat: "",
    participateLd28: false,
    note: "",
    weekRange: "08/06/2026 - 14/06/2026",
  },
  {
    id: "p17",
    stt: 17,
    name: "Phan Thùy Mai Trúc",
    phone: "-",
    rlp: "RLP Phan Thùy Mai Trúc - 31072503CC4",
    testScheduleSunday: "Có tham gia",
    scheduleTueSat: "",
    participateLd28: false,
    note: "",
    weekRange: "08/06/2026 - 14/06/2026",
  },
  {
    id: "p18",
    stt: 18,
    name: "Trần Thị Ngọc Hân",
    phone: "-",
    rlp: "RLP Trần Thị Ngọc Hân - 17052502CC4",
    testScheduleSunday: "Có tham gia",
    scheduleTueSat: "",
    participateLd28: false,
    note: "",
    weekRange: "08/06/2026 - 14/06/2026",
  },
  {
    id: "p19",
    stt: 19,
    name: "Nguyễn Thị Vân",
    phone: "985202973",
    rlp: "RLP Nguyễn Thị Vân - 16112501CC2",
    testScheduleSunday: "Có tham gia",
    scheduleTueSat: "",
    participateLd28: false,
    note: "",
    weekRange: "08/06/2026 - 14/06/2026",
  },
  {
    id: "p20",
    stt: 20,
    name: "Ngô Nguyễn Xuân Đình",
    phone: "989540641",
    rlp: "RLP Ngô Nguyễn Xuân Đình - 31072502CC2",
    testScheduleSunday: "Có tham gia",
    scheduleTueSat: "",
    participateLd28: false,
    note: "đã đi thi",
    weekRange: "08/06/2026 - 14/06/2026",
  },
  {
    id: "p21",
    stt: 21,
    name: "Võ Thụy Khánh Linh",
    phone: "-",
    rlp: "RLP Võ Thuỵ Khánh Linh - 31122501CC1",
    testScheduleSunday: "Gửi đề vào CN",
    scheduleTueSat: "chỉ học vào T7",
    participateLd28: false,
    note: "",
    weekRange: "08/06/2026 - 14/06/2026",
  },
  {
    id: "p22",
    stt: 22,
    name: "Nguyễn Thị Ngọc Hân",
    phone: "-",
    rlp: "RLP Nguyễn Thị Ngọc Hân - 26062501CC2",
    testScheduleSunday: "Có tham gia",
    scheduleTueSat: "",
    participateLd28: false,
    note: "",
    weekRange: "08/06/2026 - 14/06/2026",
  },
  {
    id: "p23",
    stt: 23,
    name: "Trần Quỳnh Trâm",
    phone: "-",
    rlp: "RLP Trần Quỳnh Trâm - 30112501CC4",
    testScheduleSunday: "Có tham gia",
    scheduleTueSat: "",
    participateLd28: false,
    note: "chỉ test được tới 11h",
    weekRange: "08/06/2026 - 14/06/2026",
  },
  {
    id: "p24",
    stt: 24,
    name: "Phùng Thị Hương Quỳnh",
    phone: "-",
    rlp: "Phùng Thị Hương Quỳnh - 08012602CC4",
    testScheduleSunday: "Có tham gia",
    scheduleTueSat: "",
    participateLd28: false,
    note: "gửi đề vào CN 19/4",
    weekRange: "08/06/2026 - 14/06/2026",
  },
  {
    id: "p25",
    stt: 25,
    name: "Hoàng Đình Quế Chi",
    phone: "-",
    rlp: "RLP Hoàng Đình Quế Chi - 30092505CC2",
    testScheduleSunday: "Có tham gia",
    scheduleTueSat: "",
    participateLd28: false,
    note: "",
    weekRange: "08/06/2026 - 14/06/2026",
  },
  {
    id: "p26",
    stt: 26,
    name: "Phùng Quốc Hùng",
    phone: "-",
    rlp: "RLP Phùng Quốc Hùng",
    testScheduleSunday: "Có tham gia",
    scheduleTueSat: "",
    participateLd28: false,
    note: "",
    weekRange: "08/06/2026 - 14/06/2026",
  },
  {
    id: "p27",
    stt: 27,
    name: "Thái Thùy Trang",
    phone: "-",
    rlp: "RLP Thái Thùy Trang",
    testScheduleSunday: "Có tham gia",
    scheduleTueSat: "",
    participateLd28: false,
    note: "",
    weekRange: "08/06/2026 - 14/06/2026",
  },
  {
    id: "p28",
    stt: 28,
    name: "Võ Ngọc Sinh",
    phone: "-",
    rlp: "RLP Võ Ngọc Sinh - 14072501CC4",
    testScheduleSunday: "Có tham gia",
    scheduleTueSat: "",
    participateLd28: false,
    note: "đi QS, 3 tuần nữa mới về",
    weekRange: "08/06/2026 - 14/06/2026",
  },
  {
    id: "p29",
    stt: 29,
    name: "Nguyễn Thị Ngọc Ánh",
    phone: "-",
    rlp: "RLP Nguyễn Thị Ngọc Ánh - 25092501CC2",
    testScheduleSunday: "Có tham gia",
    scheduleTueSat: "",
    participateLd28: false,
    note: "",
    weekRange: "08/06/2026 - 14/06/2026",
  },
  {
    id: "p30",
    stt: 30,
    name: "Hoàng Như Ngọc",
    phone: "-",
    rlp: "RLP Hoàng Như Ngọc",
    testScheduleSunday: "Có tham gia",
    scheduleTueSat: "",
    participateLd28: false,
    note: "",
    weekRange: "08/06/2026 - 14/06/2026",
  },
  {
    id: "p31",
    stt: 31,
    name: "Văn Thị Thanh Trúc",
    phone: "-",
    rlp: "RLP Văn Thị Thanh Trúc",
    testScheduleSunday: "Có tham gia",
    scheduleTueSat: "",
    participateLd28: false,
    note: "",
    weekRange: "08/06/2026 - 14/06/2026",
  },
  {
    id: "p32",
    stt: 32,
    name: "Võ Quỳnh Nga",
    phone: "-",
    rlp: "RLP Võ Quỳnh Nga",
    testScheduleSunday: "Có tham gia",
    scheduleTueSat: "",
    participateLd28: false,
    note: "",
    weekRange: "08/06/2026 - 14/06/2026",
  },
  {
    id: "p33",
    stt: 33,
    name: "Đỗ Ngọc Bảo Châu",
    phone: "-",
    rlp: "RLP Đỗ Ngọc Bảo Châu - 29012601CC4",
    testScheduleSunday: "Có tham gia",
    scheduleTueSat: "",
    participateLd28: false,
    note: "sau 1/6 mới tham gia test được",
    weekRange: "08/06/2026 - 14/06/2026",
  },
  {
    id: "p34",
    stt: 34,
    name: "Nguyễn Thị Kim Thơ",
    phone: "-",
    rlp: "RLP Nguyễn Thị Kim Thơ - 13012502CC2",
    testScheduleSunday: "Có tham gia",
    scheduleTueSat: "bạn này sẽ hong tham gia đều được",
    participateLd28: true,
    note: "xếp lịch test khác",
    weekRange: "08/06/2026 - 14/06/2026",
  },
  {
    id: "p35",
    stt: 35,
    name: "Nguyễn Hoàng Gia Linh",
    phone: "-",
    rlp: "RLP Nguyễn Hoàng Gia Linh - 27082501CC4",
    testScheduleSunday: "",
    scheduleTueSat: "",
    participateLd28: false,
    note: "",
    weekRange: "08/06/2026 - 14/06/2026",
  },
  {
    id: "p36",
    stt: 36,
    name: "Hà Võ Phương Thảo",
    phone: "-",
    rlp: "2026RLP_ONL 1:1 Hà Võ Phương Thảo",
    testScheduleSunday: "",
    scheduleTueSat: "",
    participateLd28: false,
    note: "",
    weekRange: "08/06/2026 - 14/06/2026",
  },
  {
    id: "p37",
    stt: 37,
    name: "Phạm Trương Bảo Khang",
    phone: "-",
    rlp: "RLP Phạm Trương Bảo Khang",
    testScheduleSunday: "",
    scheduleTueSat: "",
    participateLd28: false,
    note: "",
    weekRange: "08/06/2026 - 14/06/2026",
  },
  {
    id: "p38",
    stt: 38,
    name: "Lưu Nhật Huyền",
    phone: "-",
    rlp: "RLP Lưu Nhật Huyền - 29102503CC2",
    testScheduleSunday: "",
    scheduleTueSat: "",
    participateLd28: false,
    note: "",
    weekRange: "08/06/2026 - 14/06/2026",
  },
  {
    id: "p39",
    stt: 39,
    name: "Đinh Phương Thảo",
    phone: "-",
    rlp: "RLP Đinh Phương Thảo - 12012602CC4",
    testScheduleSunday: "",
    scheduleTueSat: "",
    participateLd28: true,
    note: "",
    weekRange: "08/06/2026 - 14/06/2026",
  },
  {
    id: "p40",
    stt: 40,
    name: "Nguyễn Thị Linh Chi",
    phone: "-",
    rlp: "Nguyễn Thị Linh Chi - 27072501CC4",
    testScheduleSunday: "",
    scheduleTueSat: "",
    participateLd28: true,
    note: "",
    weekRange: "08/06/2026 - 14/06/2026",
  },
  {
    id: "p41",
    stt: 41,
    name: "Lương Thanh Trúc",
    phone: "-",
    rlp: "RLP Lương Thanh Trúc - 05022601CC4",
    testScheduleSunday: "",
    scheduleTueSat: "",
    participateLd28: false,
    note: "",
    weekRange: "08/06/2026 - 14/06/2026",
  },
];

