import type { PracticeRlpSession } from "@/lib/practiceRlpApi";

/** Dữ liệu demo RLP lớp luyện đề — hiển thị khi API chưa có dữ liệu. */
export const PRACTICE_RLP_DEMO_SESSIONS: PracticeRlpSession[] = [
  {
    no: 1,
    date: "08/07/2026",
    skill: "Listening",
    contents: "Listening Section 1-2 — Form completion & map labelling (Đề tuần 27)",
    teacherNote: "Ổn phần điền từ, cần luyện thêm chính tả số và tên riêng",
    deadline: "15/07/2026",
    homeworkStatus: "submitted",
    attendance: "present",
    lessonFileUrl: "https://drive.google.com/file/d/demo-practice-rlp-1",
    homeworkFileUrl: "https://docs.google.com/document/d/demo-practice-hw-1",
    recordingUrl: "https://drive.google.com/file/d/demo-practice-rec-1",
  },
  {
    no: 2,
    date: "10/07/2026",
    skill: "Reading",
    contents: "Reading — Matching headings & True/False/Not Given (Đề tuần 27)",
    teacherNote: "Đọc kỹ đoạn đầu để bắt keyword",
    deadline: "17/07/2026",
    homeworkStatus: "submitted",
    attendance: "present",
    lessonFileUrl: "https://drive.google.com/file/d/demo-practice-rlp-2",
    homeworkFileUrl: "https://docs.google.com/document/d/demo-practice-hw-2",
    recordingUrl: "",
  },
  {
    no: 3,
    date: "15/07/2026",
    skill: "Writing",
    contents: "Writing Task 1 — Biểu đồ cột, overview & body paragraph",
    teacherNote: "Overview rõ ràng; body cần so sánh số liệu chính xác hơn",
    deadline: "22/07/2026",
    homeworkStatus: "submitted_waiting",
    attendance: "present",
    lessonFileUrl: "https://drive.google.com/file/d/demo-practice-rlp-3",
    homeworkFileUrl: "https://docs.google.com/document/d/demo-practice-hw-3",
    recordingUrl: "https://drive.google.com/file/d/demo-practice-rec-3",
  },
  {
    no: 4,
    date: "17/07/2026",
    skill: "Speaking",
    contents: "Speaking Part 2 — Describe a memorable trip",
    teacherNote: "—",
    deadline: "24/07/2026",
    homeworkStatus: "overdue",
    attendance: "absent",
    lessonFileUrl: "https://drive.google.com/file/d/demo-practice-rlp-4",
    homeworkFileUrl: "https://docs.google.com/document/d/demo-practice-hw-4",
    recordingUrl: "",
  },
  {
    no: 5,
    date: "22/07/2026",
    skill: "Listening",
    contents: "Listening Section 3-4 — Multiple choice & matching (Đề tuần 28)",
    teacherNote: "Tập trung nghe từ đồng nghĩa trong đề bài",
    deadline: "29/07/2026",
    homeworkStatus: "in_progress",
    attendance: "present",
    lessonFileUrl: "https://drive.google.com/file/d/demo-practice-rlp-5",
    homeworkFileUrl: "https://docs.google.com/document/d/demo-practice-hw-5",
    recordingUrl: "https://drive.google.com/file/d/demo-practice-rec-5",
  },
  {
    no: 6,
    date: "24/07/2026",
    skill: "Reading",
    contents: "Reading — Summary completion & flow-chart (Đề tuần 28)",
    teacherNote: "—",
    deadline: "31/07/2026",
    homeworkStatus: "in_progress",
    attendance: "present",
    lessonFileUrl: "https://drive.google.com/file/d/demo-practice-rlp-6",
    homeworkFileUrl: "https://docs.google.com/document/d/demo-practice-hw-6",
    recordingUrl: "",
  },
  {
    no: 13,
    date: "05/08/2026",
    skill: "Writing",
    contents: "Writing Task 2 — Discuss both views (Chặng 2, Đề tuần 31)",
    teacherNote: "Chặng 2: luyện outline trước khi viết full bài",
    deadline: "12/08/2026",
    homeworkStatus: "not_assigned",
    attendance: "present",
    lessonFileUrl: "https://drive.google.com/file/d/demo-practice-rlp-13",
    homeworkFileUrl: "",
    recordingUrl: "https://drive.google.com/file/d/demo-practice-rec-13",
  },
  {
    no: 14,
    date: "07/08/2026",
    skill: "Speaking",
    contents: "Speaking mock — Full test simulation (Chặng 2)",
    teacherNote: "Buổi test tập trung CN — chuẩn bị cue card Part 2",
    deadline: "14/08/2026",
    homeworkStatus: "not_assigned",
    attendance: "present",
    lessonFileUrl: "https://drive.google.com/file/d/demo-practice-rlp-14",
    homeworkFileUrl: "https://docs.google.com/document/d/demo-practice-hw-14",
    recordingUrl: "",
  },
];

export function withPracticeRlpDemoFallback(
  sessions: PracticeRlpSession[],
): PracticeRlpSession[] {
  return sessions.length > 0 ? sessions : PRACTICE_RLP_DEMO_SESSIONS;
}
