import type { RlpSessionRecord } from './rlp.types';

export const DEFAULT_RLP_SESSIONS: RlpSessionRecord[] = [
  {
    no: 1,
    date: "02/10/2025",
    skill: "Speaking",
    contents:
      "Introduction to Speaking Part 1 - chiến thuật trả lời chủ đề Work, Hobbies, Travel",
    teacherNote: "—",
    deadline: "09/10/2025",
    homeworkStatus: "not_assigned",
    attendance: "present",
  },
  {
    no: 2,
    date: "04/10/2025",
    skill: "Speaking",
    contents: "Speaking Part 2 - Descriptive language, Describe a person",
    teacherNote: "—",
    deadline: "11/10/2025",
    homeworkStatus: "not_assigned",
    attendance: "present",
  },
  {
    no: 3,
    date: "09/10/2025",
    skill: "Reading",
    contents: "Reading - Matching headings, Sentence endings",
    teacherNote: "—",
    deadline: "16/10/2025",
    homeworkStatus: "not_assigned",
    attendance: "present",
  },
  {
    no: 4,
    date: "11/10/2025",
    skill: "Speaking",
    contents: "Speaking Part 2 - Describe an item, phát âm & giọng cuối câu",
    teacherNote: "—",
    deadline: "18/10/2025",
    homeworkStatus: "not_assigned",
    attendance: "present",
  },
  {
    no: 5,
    date: "16/10/2025",
    skill: "Speaking",
    contents: "Speaking Part 3 - Chiến thuật câu hỏi, phát triển ý",
    teacherNote: "—",
    deadline: "23/10/2025",
    homeworkStatus: "not_assigned",
    attendance: "present",
  },
  {
    no: 6,
    date: "18/10/2025",
    skill: "Reading",
    contents: "Reading - Matching features, Matching information",
    teacherNote: "—",
    deadline: "25/10/2025",
    homeworkStatus: "not_assigned",
    attendance: "present",
  },
  {
    no: 7,
    date: "18/10/2025",
    skill: "Speaking",
    contents: "Speaking Part 2 - Describe a place, cleft sentence",
    teacherNote: "—",
    deadline: "25/10/2025",
    homeworkStatus: "not_assigned",
    attendance: "present",
  },
  {
    no: 8,
    date: "21/10/2025",
    skill: "Speaking",
    contents: "Speaking Part 2 & 3 liên tục, tạo ngữ cơ bản, nguyên âm đôi",
    teacherNote: "—",
    deadline: "28/10/2025",
    homeworkStatus: "not_assigned",
    attendance: "present",
  },
  {
    no: 9,
    date: "23/10/2025",
    skill: "Reading",
    contents: "Reading - Multiple choice (Passage 2)",
    teacherNote: "—",
    deadline: "30/10/2025",
    homeworkStatus: "not_assigned",
    attendance: "present",
  },
  {
    no: 10,
    date: "25/10/2025",
    skill: "Speaking",
    contents: "Speaking Part 1 - Accommodation, Sport, Transportation",
    teacherNote: "—",
    deadline: "01/11/2025",
    homeworkStatus: "not_assigned",
    attendance: "present",
  },
  {
    no: 11,
    date: "28/10/2025",
    skill: "Speaking",
    contents: "Speaking Part 2 - Story telling, Describe an experience",
    teacherNote: "—",
    deadline: "04/11/2025",
    homeworkStatus: "not_assigned",
    attendance: "present",
  },
  {
    no: 12,
    date: "30/10/2025",
    skill: "Reading",
    contents: "Reading - Information Identification (T/F/NG, Y/N/NG)",
    teacherNote: "—",
    deadline: "06/11/2025",
    homeworkStatus: "not_assigned",
    attendance: "present",
  },
  {
    no: 13,
    date: "21/04/2026",
    skill: "Writing",
    contents: "Writing Task 1 - Biểu đồ cột, cấu trúc overview & body",
    teacherNote: "—",
    deadline: "28/04/2026",
    homeworkStatus: "not_assigned",
    attendance: "present",
  },
  {
    no: 14,
    date: "23/04/2026",
    skill: "Listening",
    contents: "Listening Section 1-2 - Form completion, map labelling",
    teacherNote: "—",
    deadline: "30/04/2026",
    homeworkStatus: "not_assigned",
    attendance: "present",
  },
  {
    no: 15,
    date: "25/04/2026",
    skill: "Speaking",
    contents: "Speaking Part 2 - Describe an event (Chặng 1)",
    teacherNote: "—",
    deadline: "02/05/2026",
    homeworkStatus: "in_progress",
    attendance: "present",
  },
  {
    no: 16,
    date: "28/04/2026",
    skill: "Reading",
    contents: "Reading - Summary completion, flow-chart",
    teacherNote: "—",
    deadline: "05/05/2026",
    homeworkStatus: "not_assigned",
    attendance: "absent",
  },
  {
    no: 17,
    date: "30/04/2026",
    skill: "Writing",
    contents: "Writing Task 2 - Opinion essay outline",
    teacherNote: "—",
    deadline: "07/05/2026",
    homeworkStatus: "not_assigned",
    attendance: "present",
  },
  {
    no: 18,
    date: "05/05/2026",
    skill: "Listening",
    contents: "Listening Section 3-4 - Academic discussion",
    teacherNote: "—",
    deadline: "12/05/2026",
    homeworkStatus: "not_assigned",
    attendance: "present",
  },
  {
    no: 19,
    date: "25/05/2026",
    skill: "Speaking",
    contents: "Speaking mock round - Full test simulation",
    teacherNote: "—",
    deadline: "26/05/2026",
    homeworkStatus: "not_assigned",
    attendance: "present",
  },
  {
    no: 20,
    date: "27/05/2026",
    skill: "Reading",
    contents: "Reading intensive - Mixed question types review",
    teacherNote: "—",
    deadline: "30/05/2026",
    homeworkStatus: "not_assigned",
    attendance: "present",
  },
];
